Fix bugs introduced by setup-sslmate
cisagov/admiral pull request #39
Opened 2023-01-12 20:31 UTC by king-alexander

#  #

## 🗣 Description ##

I introduced a couple bugs to the project when I rebased #31. This small pull request fixes those mistakes.
## 💭 Motivation and context ##

These changes are required to remove my bugs from `develop`.

## 🧪 Testing ##

I corrected the inadvertent changes from rebasing #31.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).

## ✅ Pre-merge checklist ##

- [x] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2023-01-12 20:40 UTC, mcdonnnj requested changes
Please fix these badges to refer to this repository:

https://github.com/cisagov/admiral/blob/9dd0abe5f80c08e77b47a50f8be60830add11cf3/README.md?plain=1#L3-L6

2023-01-12 21:14 UTC, dav3r approved these changes
👍

2023-01-13 16:03 UTC, mcdonnnj approved these changes

2023-01-13 16:03 UTC, mcdonnnj commented on src/admiral/_version.py
> +__version__ = "1.1.0"
Just a reminder to bump the minor version.

2023-01-13 18:06 UTC, king-alexander commented on src/admiral/_version.py
> +__version__ = "1.1.0"
[6d98461](https://github.com/cisagov/admiral/pull/39/commits/6d98461ba2412e0cc43f5428b63a688231faaa0c)

2023-01-13 18:15 UTC, merged